config/routes.rb
Prayerlist::Application.routes.draw do
  get "registrations/create"

  get "reports/answered"

  get "reports/unanswered"

  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'front_page#index'

  resources :prayer_requests

  get 'prayer_request/:id/toggle_answered', to: 'prayer_requests#toggle_answered', as: :toggle_answered_prayer_request

  get '/prayer_requests/:prayer_request_id/new/', to: 'prayer_requests#new_update', as: :new_update_prayer_request
  post '/prayer_requests/:prayer_request_id/new/', to: 'prayer_requests#create_update', as: :new_update_prayer_request
  get '/prayer_requests/:prayer_request_id/edit/:prayer_update_id', to: 'prayer_requests#edit_update', as: :edit_update_prayer_request
  put '/prayer_requests/:prayer_request_id/update/:prayer_update_id', to: 'prayer_requests#update_update', as: :update_update_prayer_request
  delete '/prayer_requests/:prayer_request_id/delete/:prayer_update_id', to: 'prayer_requests#destroy_update', as: :delete_update_prayer_request

end

app/models/prayer_request.rb
class PrayerRequest < ActiveRecord::Base
  belongs_to :user  
  has_many :prayer_updates, :dependent => :destroy

  validates :user_id, :presence => true
  validates :title, :presence => true
  validates :request_text, :presence => true

  attr_accessible :user_id, :title, :request_text

  scope :descending, order("updated_at DESC")
  scope :recent, order("updated_at DESC") 
  scope :answered, where(answered: true)
  scope :unanswered, where(answered: false)

  searchable do 
    text :title, :request_text
    text :user do
      user.name
    end
    text :prayer_updates do
      prayer_updates.map { |pu| pu.body }
    end
    time :updated_at
  end

  def self.belongs_to_user(user)
    where(user_id: user.id)
  end

end

app/models/prayer_update.rb
class PrayerUpdate < ActiveRecord::Base
  # touch updates the prayer_request when a update is created or changed
  belongs_to :prayer_request, :touch => true

  attr_accessible :body, :prayer_request_id

  after_save :reindex_parent!

  def reindex_parent!
    prayer_request.index
  end

  scope :recent, order("updated_at DESC") 
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :prayer_requests, :dependent => :destroy

  validates :name, :presence => true

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :user_owned? 

  protected

  def user_owned?(user_id)
    current_user && current_user.id == user_id 
  end
end

app/controllers/front_page_controller.rb
class FrontPageController < ApplicationController
  before_filter :authenticate_user!
   
  def index
    @latest_requests = PrayerRequest.recent.paginate(page: params[:lr_page], per_page: 5)
    @latest_requests_ans = PrayerRequest.answered.recent.paginate(page: params[:lra_page], per_page: 5)
    @my_requests = PrayerRequest.belongs_to_user(current_user).descending.paginate(page: params[:mr_page], per_page: 5)
    
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/prayer_requests_controller.rb
class PrayerRequestsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @search = PrayerRequest.search do
      fulltext params[:search]
      paginate :page => params[:page], :per_page => 5
      order_by :updated_at, :desc
    end

    if params[:search].present?
      @prayer_requests =  @search.results
    else
      @prayer_requests =  PrayerRequest.recent.paginate(page: params[:page], per_page: 5)
    end
  end

  def new
    @prayer_request = PrayerRequest.new()
  end

  def create
    prayer_request = params[:prayer_request]
    p = PrayerRequest.new(prayer_request)
    p.user_id = current_user.id
    
    if p.save
      flash[:success] = "Prayer request created."
      redirect_to prayer_requests_path 
    else
      flash.now[:error] = p.errors.full_messages
      @prayer_request = p 
      render :new
    end
  end

  def show
    @prayer_request = PrayerRequest.find(params[:id])
    if @prayer_request.answered?
      @answered_text = 'Answered'
      @answered_button_style = 'success'
    else
      @answered_text = 'UnAnswered'
      @answered_button_style = 'warning'
    end
  end

  def edit
    @prayer_request = PrayerRequest.find(params[:id])
  end

  def update
    @prayer_request = PrayerRequest.find(params[:id])
    if @prayer_request.update_attributes(params[:prayer_request])
      flash.now[:success] = "Request updated."
      render :show
    else
      flash.now[:error] = "Errors below."
      render :edit
    end
  end

  def destroy
    @prayer_request = PrayerRequest.find(params[:id])
    @prayer_request.destroy()
    flash[:success] = "Request deleted."
    redirect_to prayer_requests_path
  end

  def toggle_answered
    @prayer_request = PrayerRequest.find(params[:id])
    @prayer_request.toggle(:answered)
    if @prayer_request.save
      redirect_to prayer_request_path(params[:id])
    else
      flash.now[:error] = "Errors below"
      render :show
    end 
  end

  def new_update
    @prayer_request_id = params[:prayer_request_id]
    @prayer_update = PrayerUpdate.new()
  end

  def create_update
    prayer_request_id = params[:prayer_request_id]
    p = PrayerUpdate.new(params[:prayer_update])
    p.prayer_request_id = prayer_request_id 
    
    if p.save
      flash.now[:success] = "Prayer update created."
      redirect_to prayer_request_path(prayer_request_id)
    else
      flash.now[:error] = "Errors below."
      render :edit
    end

  end

  def edit_update
    @prayer_request = PrayerRequest.find(params[:prayer_request_id])
    @prayer_update = PrayerUpdate.find(params[:prayer_update_id])
  end

  def update_update
    @prayer_update = PrayerUpdate.find(params[:prayer_update_id])
    if @prayer_update.update_attributes(params[:prayer_update])
      flash[:success] = "Request updated."
      redirect_to prayer_request_path(params[:prayer_request_id]) 
    else
      flash.now[:error] = "Errors below."
      render :edit_update
    end
  end

  def destroy_update
    @prayer_update = PrayerUpdate.find(params[:prayer_update_id])
    @prayer_update.destroy()
    flash[:success] = "Request deleted."
    redirect_to prayer_request_path(params[:prayer_request_id]) 
  end
end

app/controllers/registrations_controller.rb
# Hook to add recaptcha to devise user framework
class RegistrationsController < Devise::RegistrationsController
  def create
    if verify_recaptcha
      super
    else
      build_resource
      clean_up_passwords(resource)
      flash[:alert] = "There was an error with the recaptcha code below. Please re-enter the code and click submit."
      #render_with_scope :new
      render :new
    end
  end  
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def answered
    @prayer_requests = PrayerRequest.answered.all
  end

  def unanswered
    @prayer_requests = PrayerRequest.unanswered.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)                          
    base_title = "Prayer List"
    if page_title.empty?
        base_title
    else
        "#{page_title} | #{base_title}"
    end
  end

  def answered_image(request)
    request.answered? ? "/images/praise_icon.png" : "/images/prayer_icon.png"
  end

  def ESTed(date)
    date.in_time_zone("Eastern Time (US & Canada)")
  end

end

app/helpers/front_page_helper.rb
module FrontPageHelper
end

app/helpers/prayer_requests_helper.rb
module PrayerRequestsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/front_page/_latest_answered_requests.html.erb
<h3>Latest Answered</h3>
<div><%= @latest_requests_ans.total_entries %> Requests</div>
<table class='table table-striped'>
<% @latest_requests_ans.each do |r| %>
<tr>
  <td><%= link_to r.title, prayer_request_path(r.id) %></td>
  <td><%= I18n.l ESTed(r.updated_at) %></td>
</tr> 
<% end %>
</table>
<%= will_paginate @latest_requests_ans, param_name: 'lra_page' %>
<script type="text/javascript">
  $(function() {
    $('.pagination a').attr('data-remote', 'true');
  });
</script>

app/views/front_page/_latest_requests.html.erb
<h3>Latest Updates</h3>
<div><%= @latest_requests.total_entries %> Requests</div>
<table class='table table-striped'>
<% @latest_requests.each do |r| %>
<tr>
  <td><%= link_to r.title, prayer_request_path(r.id) %></td>
  <td><%= r.user.name %>
  <td><%= I18n.l ESTed(r.updated_at) %></td>
  <td><%= image_tag answered_image(r), width: '32px', alt: "PRAY!" %></td>
</tr> 
<% end %>
</table>
<%= will_paginate @latest_requests, param_name: 'lr_page' %>

<script type="text/javascript">
  $(function() {
    $('.pagination a').attr('data-remote', 'true');
  });
</script>

app/views/front_page/_my_requests.html.erb
<h3>My Requests</h3>
<div><%= @my_requests.total_entries %> Requests</div>
<table class='table table-striped'>
<% @my_requests.each do |r| %>
<tr>
  <td><%= link_to r.title, prayer_request_path(r.id) %></td>
  <td><%= I18n.l ESTed(r.updated_at) %></td>
  <td><%= image_tag answered_image(r), width: '32px', alt: "PRAY!" %></td>
</tr> 
<% end %>
</table>
<%= will_paginate @my_requests, param_name: 'mr_page' %>
<script type="text/javascript">
  $(function() {
    $('.pagination a').attr('data-remote', 'true');
  });
</script>

app/views/front_page/index.html.erb
<script type="text/javascript">
  $(function() {
    $('.pagination a').attr('data-remote', 'true');
  });
</script>

<% unless @latest_requests.empty? %>
  <div id="latest_requests_id"><%= render partial: "latest_requests" %></div>
<%end%>

<% unless @latest_requests_ans.empty? %>
  <div id="latest_requests_ans_id"><%= render partial: "latest_answered_requests" %></div>
<%end%>

<% unless @my_requests.empty? %>
  <div id="my_requests_id"><%= render partial: "my_requests" %></div>
<%end%>

app/views/front_page/index.js.erb
$("#latest_requests_ans_id").html("<%= escape_javascript(render(partial: "latest_answered_requests")) %>");
$("#latest_requests_id").html("<%= escape_javascript(render(partial: "latest_requests")) %>");
$("#my_requests_id").html("<%= escape_javascript(render(partial: "my_requests")) %>");

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Supported by Kevin Lester
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top ">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Prayer List", '/', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    '/' %></li>          
          <% if signed_in? %>
            <li><%= link_to "Create Request", new_prayer_request_path%></li>
            <li><%= link_to "Search", prayer_requests_path %></li>
            <li class="dropdown">
              <%= link_to raw("Reports<i class='caret'></i>"), "#", class: 'dropdown-toggle', "data-toggle" => "dropdown" %>
              <ul class="dropdown-menu">
                <li><%= link_to "Unanswered", reports_unanswered_path %></li>
                <li><%= link_to "Answered", reports_answered_path %></li>
              </ul>
            </li>
            <li><%= link_to "Profile", edit_user_registration_path%></li>
            <li><%= link_to "Sign out | (#{current_user.email})", destroy_user_session_path, method: "delete" %>
            </li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_messages.html.erb
<% if value.kind_of?(Array) %>
  <ul>
  <% value.each do |v| %>
    <li><%= v %></li>
  <% end %> 
  <ul>
<% else %>
  <%= value %>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">      
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= render 'layouts/messages', value: value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/prayer_requests/edit.html.erb
<%=form_for @prayer_request, :html => {:class => "form-horizontal"} do |p|%>
  <div class="control-group"> 
    <%= p.label :title, class: 'control-label' %>
    <div class="controls">
      <%= p.text_field :title %>
    </div>
  </div>  
  <div class="controls">
    <%= p.text_area :request_text, :autofocus => true %>
  </div>
  <br/>
  <div class="controls">
    <%= p.submit 'Update', class: "btn btn-large btn-primary" %>
    <%= link_to 'Cancel', prayer_request_path(@prayer_request.id), class: "btn btn-large" %>
  </div>
<%end%>

app/views/prayer_requests/edit_update.html.erb
<%= form_for @prayer_update, url: update_update_prayer_request_path(@prayer_request.id, @prayer_update.id), html: {class: "form-horizontal"} do |f| %>
  <div class="controls">
    <%= f.text_area :body, :autofocus => true %> 
  </div>
  <br/>
  <div class="controls">
    <%= f.submit 'Save', class: "btn btn-large btn-primary" %>
    <%= link_to 'Cancel', prayer_request_path(@prayer_request.id), class: "btn btn-large" %>
  </div>
<%end%>

app/views/prayer_requests/index.html.erb
<%= form_tag prayer_requests_path, :method => :get, class: 'form-search' do %>
<p>
  <%= text_field_tag :search, params[:search], autofocus: true, class: "input-medium search-query" %>
  <%= submit_tag "Search", :name => nil, class:'btn btn-medium btn-info' %>
 </p>
 <% end %>

<div><%= @prayer_requests.total_entries %> Requests</div>
<table class="table table-striped table-bordered table-condensed">
<tr>
  <th>Title</th>
  <th>Author</th>
  <th>Updated At</th>
</tr>
<% @prayer_requests.each do |pr| %>
  <tr>
    <td><%= link_to pr.title, prayer_request_path(pr.id)  %></td>
    <td><%= User.find(pr.user_id).name %></td>
    <td><%= I18n.l ESTed(pr.updated_at) %>
  </tr>
<% end %>
</table>
<%= will_paginate @prayer_requests %>

app/views/prayer_requests/new.html.erb
<%= form_for(@prayer_request, url: prayer_requests_path, html: {class: 'form-horizontal'}) do |f| %>
  <div class="control-group">
    <div class="control-label"><%= f.label :title %></div>
    <div class="controls"><%= f.text_field :title, :autofocus => true %></div>
  </div>
  <div class="control-group">
    <div class="control-label"><%= f.label :request_text %></div>
    <div class="controls"><%= f.text_area :request_text %></div>
  </div>

  <div class="controls">
    <%= f.submit "Create", class: "btn btn-large btn-primary"%>
  </div>
<% end %>

app/views/prayer_requests/new_update.html.erb
<%= form_for(@prayer_update, url: new_update_prayer_request_path(@prayer_request_id), html: {class: 'form-horizontal'}) do |f| %>
  <div class="control-group">
    <div class="controls">
      <%= f.text_area :body, :autofocus => true %>
    </div>
  </div>

  <div class="controls">
    <%= f.submit 'Save', class: "btn btn-large btn-primary" %>
    <%= link_to 'Cancel', prayer_request_path(@prayer_request_id), class: "btn btn-large" %>
  </div>
<%end%>

app/views/prayer_requests/show.html.erb
<h1><%= @prayer_request.title %></h1>
<p><%= I18n.l ESTed(@prayer_request.updated_at)%></p>

<div>
  <%= link_to "get PDF", prayer_request_path(@prayer_request.id, format: :pdf), class: "btn btn-small btn-primary"%>
</div>

<div class="well">
  <%= simple_format(@prayer_request.request_text) %>
</div>

<% if user_owned?(@prayer_request.user_id) %>
<div>
  <%= link_to 'Edit', edit_prayer_request_path(@prayer_request.id), class: "btn btn-medium btn-primary" %>
  <%= link_to 'Delete', prayer_request_path(@prayer_request.id), data: { confirm: "Are you sure?" }, method: 'delete', class: "btn btn-medium btn-danger" %>
  <%= link_to @answered_text, toggle_answered_prayer_request_path(@prayer_request.id), class: "btn btn-medium btn-#{@answered_button_style}"%>
  <%= link_to 'Add Update', new_update_prayer_request_path(@prayer_request.id), class: "btn btn-medium btn-primary" %>
</div>
<%end%>

<% if !@prayer_request.prayer_updates.empty?%>
<h2>Updates</h2>
<%end%>
<% @prayer_request.prayer_updates.each do |u|%>
<p><%= I18n.l ESTed(u.updated_at)%></p>
<div class="well">
  <%= simple_format(u.body) %><br/>
</div>
<% if user_owned?(@prayer_request.user_id) %>
<div class="well well-small">
  <%= link_to 'edit', edit_update_prayer_request_path(@prayer_request.id, u.id), class: "btn btn-small btn-primary" %>
  <%= link_to 'delete', delete_update_prayer_request_path(@prayer_request.id, u.id), data: { confirm: "Are you sure?" }, method: 'delete', class: "btn btn-small btn-danger" %>
</div>
<%end%>
<%end%>

app/views/reports/answered.html.erb
<h1>Answered Prayer Requests</h1>

<form>
  <textarea>
  <% @prayer_requests.each do |r| %>
<%= r.title %> on <%= I18n.l ESTed(r.updated_at) %>
<%= r.request_text %>
<%= '-'*50 %>

<% unless r.prayer_updates.empty? %>
Last Update
<%= r.prayer_updates.last.body %>
<%= '='*50 %>
<%end%>
  <% end %>
  </textarea>

</form>

<p><%= link_to "get PDF", reports_answered_path(:format => 'pdf'), class: "btn btn-medium btn-primary" %></p>

app/views/reports/unanswered.html.erb
<h1>Unanswered Prayer Requests</h1>

<form>
  <textarea>
  <% @prayer_requests.each do |r| %>
<%= r.title %> on <%= I18n.l ESTed(r.updated_at) %>
<%= r.request_text %>
<%= '-'*50 %>
<% unless r.prayer_updates.empty? %>
Last Update
<%= r.prayer_updates.last.body %>
<%= '='*50 %>
<% end %>
  <% end %>
  </textarea>
</form>

<p><%= link_to "get PDF", reports_unanswered_path(:format => 'pdf'), class: "btn btn-medium btn-primary" %></p>